def header(page,l,t):
 nav="".join(f'<a href="{route(p,l)}" '+('aria-current="page"' if p==page else '')+f'>{esc(label)}</a>' for p,label in zip(["services","projects","about"],t["nav"]))
 langs="".join(f'<a href="{route(page,x)}" lang="{x}" aria-label="{name}" '+('aria-current="true"' if x==l else '')+f'>{x.upper()}</a>' for x,name in [("sq","Shqip"),("en","English"),("de","Deutsch")])
 return f'''<a class="skip" href="#main">{t["skip"]}</a><header class="header"><div class="wrap header-inner"><a class="brand" href="{route("index",l)}" aria-label="IT Department"><img src="assets/brand/logo-original.png" width="480" height="232" alt="IT Department"></a><nav class="desktop-nav" aria-label="{t["menu"]}">{nav}</nav><div class="header-actions"><nav class="languages" aria-label="{t["lang"]}">{langs}</nav><a class="header-cta" href="{route("contact",l)}">{t["talk"]}{A}</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav"><span>{t["menu"]}</span><span class="menu-lines" aria-hidden="true"></span></button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="{t["menu"]}" hidden>{nav}<a href="{route("contact",l)}">{t["contact"]}</a></nav></header>'''

def footer(l,t):
 links="".join(f'<a href="{route(p,l)}">{esc(label)}</a>' for p,label in [("services",t["nav"][0]),("projects",t["nav"][1]),("about",t["nav"][2]),("creative","Kreativa" if l=="sq" else "Creative"),("ai-agents","AI Agents" if l!="de" else "KI-Agenten"),("contact",t["contact"])])
 return f'''<footer class="footer"><div class="wrap"><div class="footer-top"><a class="brand" href="{route("index",l)}"><img src="assets/brand/logo-original.png" width="480" height="232" alt="IT Department"></a><p>{t["footer"]}</p><a href="mailto:{cfg["email"]}">{cfg["email"]}{A}</a></div><div class="footer-mid"><nav>{links}</nav><div><a href="https://www.instagram.com/it.department_" target="_blank" rel="noopener noreferrer">Instagram {A}</a><a href="https://www.linkedin.com/company/itdks/" target="_blank" rel="noopener noreferrer">LinkedIn {A}</a></div></div><div class="footer-bottom"><span>© 2026 IT Department · {t["location"]}</span><nav><a href="{route("privacy",l)}">{t["privacy"]}</a><a href="{route("terms",l)}">{t["terms"]}</a></nav></div></div></footer>'''

def home(l,t):
 c={
 "sq":{"heading":["Biznesi yt.","I lidhur. I mbështetur."],"kicker":"TEKNOLOGJI QË PUNON PËR BIZNESIN","intro":"Nga faqja e parë web te sistemet që mbajnë punën në lëvizje. Zhvillim, automatizim dhe IT — me një partner që i lidh të gjitha.","cta":"Diskuto projektin","second":"Eksploro shërbimet","bottom":"Prishtinë, Kosovë / Partneri yt në teknologji","figure":"Web, softuer dhe infrastrukturë si pjesë të lidhura të biznesit","stack":["Prezenca jote","Proceset e tua","Baza teknike"],"stacktitle":"Të gjitha pjesët. Një drejtim.","stacknote":"WEB / SOFTWARE / IT","servicesHeading":"Çfarë e çon biznesin tënd përpara?","servicesIntro":"Tri pika nisjeje. Zgjidh atë që të duhet tani; pjesën tjetër e lidhim bashkë.","tabs":["Prezencë","Organizim","Mbështetje"],"panel":["Nga përshtypja e parë,<br>te kontakti i radhës.","Puna rrjedh më mirë<br>kur sistemet lidhen.","Një bazë më e fortë<br>për çdo ditë pune."],"diagram":[["STRUKTURË WEB","Identitet","Shërbime","Kontakt"],["RRJEDHË PUNE","Kërkesa","Procesi","Raporti"],["INFRASTRUKTURË","Qasjet","Siguria","Backup"]],"link":"Shiko zgjidhjet","note":"Fillojmë me nevojën. Pastaj zgjedhim teknologjinë.","how":"Zhvillim · Integrim · Mirëmbajtje"},
 "en":{"heading":["Your business.","Connected. Supported."],"kicker":"TECHNOLOGY THAT WORKS FOR BUSINESS","intro":"From your first website to the systems that keep work moving. Development, automation and IT — with one partner to connect it all.","cta":"Discuss your project","second":"Explore our services","bottom":"Prishtina, Kosovo / Your technology partner","figure":"Web, software and infrastructure as connected parts of a business","stack":["Your presence","Your processes","Your foundation"],"stacktitle":"Every piece. One direction.","stacknote":"WEB / SOFTWARE / IT","servicesHeading":"What moves your business forward?","servicesIntro":"Three starting points. Choose what you need today; we connect the rest.","tabs":["Presence","Organization","Support"],"panel":["From a first impression<br>to the next conversation.","Work flows better<br>when systems connect.","A stronger foundation<br>for every working day."],"diagram":[["WEB STRUCTURE","Identity","Services","Contact"],["WORKFLOW","Enquiry","Process","Report"],["INFRASTRUCTURE","Access","Security","Backup"]],"link":"Explore the solutions","note":"We start with your needs. Then choose the technology.","how":"Development · Integration · Maintenance"},
 "de":{"heading":["Ihr Unternehmen.","Vernetzt. Unterstützt."],"kicker":"TECHNOLOGIE FÜR IHR UNTERNEHMEN","intro":"Von der ersten Website bis zu den Systemen für den Arbeitsalltag. Entwicklung, Automatisierung und IT — mit einem Partner, der alles verbindet.","cta":"Projekt besprechen","second":"Leistungen entdecken","bottom":"Prishtina, Kosovo / Ihr Technologiepartner","figure":"Web, Software und Infrastruktur als verbundene Bereiche eines Unternehmens","stack":["Ihr Auftritt","Ihre Prozesse","Ihre technische Basis"],"stacktitle":"Alle Bausteine. Eine Richtung.","stacknote":"WEB / SOFTWARE / IT","servicesHeading":"Was bringt Ihr Unternehmen voran?","servicesIntro":"Drei Ausgangspunkte. Wählen Sie, was Sie heute brauchen; wir verbinden den Rest.","tabs":["Auftritt","Organisation","Support"],"panel":["Vom ersten Eindruck<br>zum nächsten Kontakt.","Bessere Abläufe durch<br>verbundene Systeme.","Eine stärkere Basis<br>für jeden Arbeitstag."],"diagram":[["WEB-STRUKTUR","Identität","Leistungen","Kontakt"],["ARBEITSABLAUF","Anfrage","Prozess","Bericht"],["INFRASTRUKTUR","Zugang","Sicherheit","Backup"]],"link":"Lösungen ansehen","note":"Wir beginnen mit Ihrem Bedarf. Dann wählen wir die Technologie.","how":"Entwicklung · Integration · Wartung"}
 }[l]
 svg=f'''<svg class="architecture-svg" viewBox="0 0 640 520" role="img" aria-label="{c["figure"]}" xmlns="http://www.w3.org/2000/svg">
 <defs><linearGradient id="plate" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#222631"/><stop offset=".55" stop-color="#101217"/><stop offset="1" stop-color="#141720"/></linearGradient><linearGradient id="edge" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#ff6c62"/><stop offset=".5" stop-color="#f21b1b"/><stop offset="1" stop-color="#761b20"/></linearGradient><linearGradient id="glass" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#301a21"/><stop offset=".65" stop-color="#15141b"/><stop offset="1" stop-color="#21232d"/></linearGradient><pattern id="grid" width="28" height="16" patternUnits="userSpaceOnUse"><path d="M28 0H0V16" fill="none" stroke="#ffffff" stroke-opacity=".045"/></pattern></defs>
 <path d="M28 365L320 519 618 350M28 310L320 464 618 295M28 255L320 409 618 240M28 200L320 354 618 185" stroke="#ffffff" stroke-opacity=".045" fill="none"/>
 <path d="M86 132V352M322 26V478M556 137V350" stroke="#ed3739" stroke-opacity=".2" stroke-dasharray="3 8"/>
 <g class="stack-layer layer-infra"><path d="M86 332L322 461 559 332V347L322 479 86 347Z" fill="#13151c" stroke="#3a3b46"/><path d="M86 332L322 204 559 332 322 461Z" fill="url(#plate)" stroke="#505360"/><path d="M117 331L322 221 528 332 322 445Z" fill="url(#grid)" stroke="#2b303c"/><path d="M147 333L322 238 498 333 322 428Z" fill="none" stroke="#d33740" stroke-opacity=".6"/><path d="M171 331L322 250 474 331 322 413Z" fill="none" stroke="#6d333b" stroke-dasharray="3 5"/><path d="M86 347L322 479 559 347" fill="none" stroke="url(#edge)" stroke-width="2"/><path d="M157 369l20 11m9 5 20 11m9 5 20 11" stroke="#e44040" stroke-width="3"/></g>
 <g class="stack-layer layer-system"><path d="M76 240L322 374 569 240V255L322 390 76 255Z" fill="#13151a" stroke="#343541"/><path d="M76 240L322 107 569 240 322 374Z" fill="url(#glass)" stroke="#734149"/><path d="M76 255L322 390 569 255" fill="none" stroke="#91242d"/><g fill="#252733" stroke="#60616c"><path d="M164 241l63-34 63 34-63 34Z"/><path d="M267 241l56-31 56 31-56 31Z" fill="#bc202b" stroke="#fb6e71"/><path d="M362 241l63-34 63 34-63 34Z"/></g><path d="M287 241h-1m94 0h43M290 241H267" stroke="#ff6569" stroke-width="2"/><path d="M227 208V172M323 209V151M424 207V170" stroke="#f75964" stroke-opacity=".6" stroke-dasharray="3 5"/><path d="M111 242L322 128 534 242" fill="none" stroke="#9b434e" stroke-opacity=".4"/></g>
 <g class="stack-layer layer-web"><path d="M87 143L322 270 557 143V157L322 286 87 157Z" fill="#1e2029" stroke="#5c4b52"/><path d="M87 143L322 16 557 143 322 270Z" fill="url(#plate)" stroke="#e66a70" stroke-opacity=".8"/><path d="M121 143L322 34 523 143 322 252Z" fill="#11141b" stroke="#4f4c58"/><path d="M137 134L337 243M151 126L352 235" stroke="#292d38"/><path d="M168 117L323 34M174 124L329 41" stroke="#353843"/>
 <path d="M202 108l78-42 69 37-77 43Z" fill="#ba2531"/><path d="M286 153l78-43 72 39-79 43Z" fill="#2b2e3b" stroke="#4c505e"/><path d="M232 164l40-22 21 12-41 22Z" fill="#202432" stroke="#494c5a"/><path d="M262 181l40-22 21 12-41 22Z" fill="#202432" stroke="#494c5a"/><path d="M292 198l40-22 21 12-41 22Z" fill="#202432" stroke="#494c5a"/><path d="M223 108l55-30m-44 37 39-21" stroke="#ffacaf" stroke-width="2" opacity=".6"/><path d="M307 152l48-26m-37 33 59-32m-48 38 44-24" stroke="#9b9da9" stroke-width="2" opacity=".6"/>
 <path d="M87 157L322 286 557 157" fill="none" stroke="url(#edge)" stroke-width="2"/></g>
 <g fill="#f8555e"><circle cx="86" cy="143" r="3"/><circle cx="557" cy="143" r="3"/><circle cx="322" cy="286" r="4"/><circle cx="322" cy="390" r="3"/><circle cx="322" cy="479" r="3"/></g></svg>'''
 figure=f'<figure class="architecture"><div class="architecture-meta"><span>{c["stacknote"]}</span><span>01—03</span></div><div class="architecture-stage">{svg}<span class="stack-caption caption-web"><b>01</b>{c["stack"][0]}</span><span class="stack-caption caption-system"><b>02</b>{c["stack"][1]}</span><span class="stack-caption caption-infra"><b>03</b>{c["stack"][2]}</span></div><figcaption><span class="red-dot"></span>{c["stacktitle"]}<span class="architecture-cross" aria-hidden="true">+</span></figcaption></figure>'
 tabs="";panels=""
 for i,(group,anchor) in enumerate(zip(t["groups"],["presence","operations","support"])):
  tabs+=f'<button class="need-tab" id="need-tab-{i}" role="tab" aria-controls="need-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}"><span class="need-tab-number">0{i+1}</span><span><strong>{group[0]}</strong><b class="need-tab-short">{c["tabs"][i]}</b><small>{group[2]}</small></span><span class="need-tab-arrow" aria-hidden="true">↗</span></button>'
  d=c["diagram"][i]
  if i==0:
   drawing=f'<div class="web-preview" aria-hidden="true"><div class="preview-bar"><i></i><i></i><i></i><span>{d[0]}</span></div><div class="web-preview-inner"><div class="wire-nav"><b></b><i></i><i></i><i></i></div><div class="wire-hero"><div><span></span><strong></strong><strong></strong><i></i><b></b></div><div class="wire-art"><span></span><span></span><span></span></div></div><div class="wire-footer"><span>{d[1]}</span><span>{d[2]}</span><span>{d[3]}</span></div></div></div>'
  elif i==1:
   drawing=f'<div class="flow-preview" aria-hidden="true"><div class="diagram-top"><span>{d[0]}</span><span>→</span></div><div class="flow-nodes"><div><b>01</b><strong>{d[1]}</strong><span></span></div><i>→</i><div class="flow-node-main"><b>02</b><strong>{d[2]}</strong><span></span></div><i>→</i><div><b>03</b><strong>{d[3]}</strong><span></span></div></div><div class="flow-return"></div></div>'
  else:
   drawing=f'<div class="infra-preview" aria-hidden="true"><div class="diagram-top"><span>{d[0]}</span><span>+</span></div><div class="infra-core"><span></span><span></span><span></span><span></span><span></span></div><div class="infra-labels"><span>{d[1]}</span><span>{d[2]}</span><span>{d[3]}</span></div></div>'
  panels+=f'<section class="need-panel" id="need-panel-{i}" role="tabpanel" aria-labelledby="need-tab-{i}" tabindex="0" {"" if i==0 else "hidden"}><div class="need-panel-copy"><span class="panel-index">0{i+1} / IT DEPARTMENT</span><h3>{c["panel"][i]}</h3><p>{group[1]}</p><a class="text-link" href="{route("services",l)}#{anchor}">{c["link"]}{A}</a></div><div class="need-panel-drawing">{drawing}</div></section>'
 return f'''<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="red-dot"></span>{c["kicker"]}</p><h1>{c["heading"][0]}<br><span>{c["heading"][1]}</span></h1><p class="intro">{c["intro"]}</p><div class="hero-actions">{button(c["cta"],route("contact",l))}<a class="hero-secondary" href="#solutions">{c["second"]}<span aria-hidden="true">↘</span></a></div><p class="hero-note">{c["note"]}</p></div>{figure}</section><div class="location-strip wrap"><span>{c["bottom"]}</span><span>{c["how"]}</span><a href="#solutions" aria-label="{c["second"]}">↓</a></div><section class="needs-section wrap" id="solutions"><div class="section-heading"><div><p class="eyebrow">{t["services"]}</p><h2>{c["servicesHeading"]}</h2></div><p>{c["servicesIntro"]}</p></div><div class="needs-explorer"><div class="need-tabs" role="tablist" aria-label="{t["services"]}" aria-orientation="vertical">{tabs}</div><div class="need-panels">{panels}</div></div></section>{work(l,t,True)}{process(l,t)}{ending(l,t)}'''

def work(l,t,home=False):
 cards=""
 for i,(key,label) in enumerate([("nexus","NEXUS"),("hyperlink","HYPERLINK")]):
  cards+=f'<a class="work-card" href="assets/creative/{key}-brandbook.webp" data-lightbox="{label}" aria-label="{t["view"]}: {label}"><div class="work-image work-{key}"><span class="work-tag">{t["concept"]}</span><img src="assets/creative/{key}-brandbook.webp" width="1024" height="1536" loading="lazy" alt="{label} — {t["concept"]}"><span class="work-open" aria-hidden="true">↗</span></div><div class="work-caption"><div><h3>{label}</h3><p>Brandbook / {t["concept"]}</p></div><span aria-hidden="true">0{i+1}</span></div></a>'
 more=f'<a class="text-link" href="{route("projects",l)}">{t["allwork"]}{A}</a>' if home else ""
 return f'<section class="work-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">{t["work"]}</p><h2>{t["workHeading"]}</h2><p>{t["workIntro"]}</p></div>{more}</div><div class="work-grid">{cards}</div></div></section>'

def process(l,t):
 steps="".join(f'<article><span class="step-number">0{i+1}</span><div><h3>{s[0]}</h3><p>{s[1]}</p></div></article>' for i,s in enumerate(t["steps"]))
 return f'<section class="process-section wrap"><div class="section-heading"><div><p class="eyebrow">{t["process"]}</p><h2>{t["processHeading"]}</h2></div><a class="text-link" href="{route("about",l)}">{t["aboutlink"]}{A}</a></div><div class="steps">{steps}</div></section>'

def ending(l,t):
 return f'<div class="ending-band"><section class="ending wrap"><div><p class="eyebrow">{t["talk"]}</p><h2>{t["ending"]}</h2></div><div><p>{t["endingbody"]}</p>{button(t["talk"],route("contact",l))}</div></section></div>'
