# Content and components for the supplied 33-page proposal.
def tr(l,sq,en,de): return {"sq":sq,"en":en,"de":de}[l]
PAGES=["index","services","projects","partners","creative","ai-agents","about","contact","krakenos"]
NAV_ORDER=['index','services','projects','partners','krakenos','creative','ai-agents','about','contact']
def labels(l): return tr(l,["Kreu","Shërbimet","Projektet","Partnerët","Kreativa","AI Agents","Rreth nesh","Kontakt","KrakenOS"],["Home","Services","Projects","Partners","Creative","AI Agents","About us","Contact","KrakenOS"],["Start","Leistungen","Projekte","Partner","Kreativ","KI-Agenten","Über uns","Kontakt","KrakenOS"])
def copy(l):
 return {
 "home":tr(l,"Teknologji që ta lehtëson punën.","Technology that makes work easier.","Technologie, die Ihre Arbeit erleichtert."),
 "homelead":tr(l,"Një partner për faqen, sistemet, sigurinë dhe idetë që duan të kthehen në punë reale.","One partner for your website, systems, security and ideas ready to become real work.","Ein Partner für Ihre Website, Systeme, Sicherheit und Ideen, die Wirklichkeit werden sollen."),
 "services":tr(l,"Çfarë do të rregullojmë sot?","What shall we improve today?","Was verbessern wir heute?"),
 "projects":tr(l,"Puna që mund ta shohësh.","Work you can see.","Arbeit, die sichtbar wird."),
 "partners":tr(l,"Me kë ndërtojmë zgjidhje më të forta.","The technologies behind stronger solutions.","Technologien für stärkere Lösungen."),
 "partnerlead":tr(l,"Platformat, mjetet dhe infrastruktura që lidhim me nevojën e projektit tënd.","Platforms, tools and infrastructure connected around your project’s needs.","Plattformen, Werkzeuge und Infrastruktur, passend zu Ihrem Projekt."),
 "about":tr(l,"Një ekip brenda rrjedhës suaj.","A team that fits the way you work.","Ein Team, das Ihre Abläufe versteht."),
 "contact":tr(l,"Nisemi nga ajo që të duhet.","Let’s start with what you need.","Beginnen wir mit Ihrem Bedarf."),
 "all":tr(l,"Të gjitha","All","Alle"),
 "families":tr(l,["Web & softuer","IT & siguri","AI Agents","Kreativa"],["Web & software","IT & security","AI Agents","Creative"],["Web & Software","IT & Sicherheit","KI-Agenten","Kreativ"]),
 "familydesc":tr(l,["Faqe, aplikacione dhe sisteme që lidhin punën.","Rrjete, siguri dhe mbështetje për çdo ditë.","Më pak detyra të përsëritura. Më shumë kontroll.","Identitet, përmbajtje dhe fushata që dallohen."],["Websites, applications and systems that connect your work.","Networks, security and support for the everyday.","Less repetitive work. More control.","Identity, content and campaigns that stand out."],["Websites, Anwendungen und Systeme für verbundene Abläufe.","Netzwerke, Sicherheit und Support im Alltag.","Weniger Routine. Mehr Kontrolle.","Identität, Inhalte und Kampagnen, die auffallen."]),
 "see":tr(l,"Shiko shërbimet","Explore services","Leistungen ansehen"),
 "book":tr(l,"Cakto takim","Book a meeting","Termin vereinbaren"),
 "details":tr(l,"Shiko detajet","Explore details","Details ansehen"),
 "request":tr(l,"Kërko një vlerësim","Discuss your project","Projekt besprechen"),
 "flow":tr(l,"Nga kërkesa te zgjidhja","From request to solution","Von der Anfrage zur Lösung"),
 "flowsteps":tr(l,["Kuptojmë","Ndërtojmë","Mbështesim"],["Understand","Build","Support"],["Verstehen","Entwickeln","Begleiten"]),
 "selected":tr(l,"Pak nga puna jonë.","A closer look at our work.","Ein Einblick in unsere Arbeit."),
 "casetitle":tr(l,"Proces më i qartë për ekipin.","A clearer process for the team.","Klarere Abläufe für das Team."),
 "casefull":tr(l,"Raporte dhe aprovime me më pak hapa.","Reports and approvals in fewer steps.","Berichte und Freigaben mit weniger Schritten."),
 "casebadge":tr(l,"Rast ilustrues · Softuer","Illustrative case · Software","Beispielszenario · Software"),
 "result":tr(l,"Rezultati i synuar","Intended result","Angestrebtes Ergebnis"),
 "stepnames":tr(l,["Kuptojmë","Planifikojmë","Realizojmë","Përmirësojmë"],["Understand","Plan","Deliver","Improve"],["Verstehen","Planen","Umsetzen","Verbessern"]),
 "stepdesc":tr(l,["Nisim nga ajo që të pengon sot.","Përcaktojmë rrugën, afatin dhe përgjegjësitë.","Ndërtojmë, provojmë dhe dorëzojmë.","Matim, mësojmë dhe qëndrojmë pranë."],["Start with what gets in your way today.","Agree on the scope, timing and responsibilities.","Build, test and hand over.","Measure, learn and stay close."],["Wir beginnen bei Ihren heutigen Hindernissen.","Umfang, Zeitplan und Verantwortung festlegen.","Entwickeln, prüfen und übergeben.","Messen, lernen und weiter begleiten."]),
 "company":tr(l,"Kompania","Company","Unternehmen"),
 "phone":tr(l,"Telefoni (opsional)","Phone (optional)","Telefon (optional)"),
 "send":tr(l,"Dërgo kërkesën","Send enquiry","Anfrage senden"),
 "sending":tr(l,"Duke dërguar…","Sending…","Wird gesendet…"),
 "success":tr(l,"Kërkesa u dërgua. Faleminderit — do të të kontaktojmë në emailin e dhënë.","Your enquiry was sent. Thank you — we’ll contact you at the email you provided.","Ihre Anfrage wurde gesendet. Vielen Dank — wir melden uns unter Ihrer E-Mail-Adresse."),
 "failure":tr(l,"Dërgimi nuk u konfirmua. Teksti yt është ruajtur. Provo përsëri ose na shkruaj me email.","Sending could not be confirmed. Your text is saved. Try again or email us directly.","Der Versand konnte nicht bestätigt werden. Ihr Text bleibt erhalten. Versuchen Sie es erneut oder schreiben Sie uns direkt."),
 "invalid":tr(l,"Plotëso këtë fushë.","Please complete this field.","Bitte füllen Sie dieses Feld aus."),
 "formnote":tr(l,"Me dërgimin, të dhënat e kësaj kërkese kalojnë përmes Formspree për t’u trajtuar nga IT Department.","Submitting sends your enquiry through Formspree to IT Department.","Beim Senden wird Ihre Anfrage über Formspree an IT Department übermittelt."),
 "count":tr(l,"rezultate","results","Ergebnisse"),
 "faqgroups":tr(l,["Bashkëpunimi","Shërbimet","Procesi","Mbështetja"],["Working together","Services","Process","Support"],["Zusammenarbeit","Leistungen","Ablauf","Support"]),
 "screenshot":tr(l,"Pamje nga prezantimi i produktit","Image from the product presentation","Ansicht aus der Produktpräsentation"),
 "demo":tr(l,"Kërko një demo","Request a demo","Demo anfragen"),
 "privacy":tr(l,"Ky version nuk përdor analytics apo cookies. Drafti i formularit ruhet vetëm në këtë skedë (sessionStorage) deri kur skeda mbyllet ose kërkesa dërgohet me sukses. Kur shtyp Dërgo kërkesën, emri, emaili dhe të dhënat që plotëson dërgohen përmes Formspree te IT Department. Një dështim i lidhjes mund të mos e konfirmojë dërgimin; kontakto me email nëse nuk je i sigurt. Calendly, WhatsApp dhe Formspree kanë politikat e tyre. Mos dërgo fjalëkalime ose të dhëna të ndjeshme. Për pyetje: info@itdks.tech.","This version uses no analytics or cookies. Form drafts stay in this tab (sessionStorage) until the tab closes or the enquiry is successfully sent. When you select Send enquiry, your name, email and entered details are sent through Formspree to IT Department. A connection failure may leave delivery unconfirmed; email us if you are unsure. Calendly, WhatsApp and Formspree have their own policies. Do not submit passwords or sensitive information. Questions: info@itdks.tech.","Diese Version verwendet keine Analyse oder Cookies. Formularentwürfe bleiben in diesem Tab (sessionStorage), bis er geschlossen oder die Anfrage erfolgreich gesendet wird. Wenn Sie Anfrage senden wählen, werden Name, E-Mail und Ihre Angaben über Formspree an IT Department übermittelt. Bei Verbindungsfehlern kann der Versand unbestätigt bleiben; schreiben Sie uns im Zweifelsfall per E-Mail. Calendly, WhatsApp und Formspree haben eigene Richtlinien. Senden Sie keine Passwörter oder sensiblen Daten. Fragen: info@itdks.tech.")}

def icon(kind=0):
 paths=['<rect x="3" y="4" width="18" height="15" rx="2"/><path d="M3 9h18M8 4v5m1 5-2 2 2 2m6-4 2 2-2 2"/>','<path d="m12 3 8 3v6c0 5-8 9-8 9S4 17 4 12V6Z"/><path d="m8 12 3 3 5-6"/>','<rect x="4" y="7" width="16" height="13" rx="4"/><path d="M12 3v4M2 12h2m16 0h2M8 12v2m8-2v2m-7 3h6"/>','<path d="m15 3 6 6-12 12H3v-6Z M12 6l6 6M3 15l6 6"/>']
 return '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[kind%4]+'</svg>'
def button(text,href,extra="",style=""): return f'<a class="button {style}" href="{esc(href)}" {extra}>{esc(text)}{A}</a>'
def heading(kicker,title,desc="",action=""):
 return f'<div class="section-heading"><div><p class="eyebrow">{esc(kicker)}</p><h2>{esc(title)}</h2>{f"<p>{esc(desc)}</p>" if desc else ""}</div>{action}</div>'
def intro(title,desc,t,kicker="IT DEPARTMENT"):
 return f'<section class="page-intro wrap"><p class="eyebrow">{esc(kicker)}</p><h1>{esc(title)}</h1>{f"<p class=lead>{esc(desc)}</p>" if desc else ""}</section>'
def header(page,l,t):
 nav=''.join(f'<a href="{route(p,l)}" '+('aria-current="page"' if p==page else '')+f'>{esc(label)}</a>' for p,label in [(key,dict(zip(PAGES,labels(l)))[key]) for key in NAV_ORDER])
 langs=''.join(f'<a href="{route(page,x)}" lang="{x}" aria-label="{name}" '+('aria-current="true"' if x==l else '')+f'>{x.upper()}</a>' for x,name in [("sq","Shqip"),("en","English"),("de","Deutsch")])
 variant={"creative":"creative","ai-agents":"ai"}.get(page,"original")
 return f'''<a class="skip" href="#main">{t['skip']}</a><header class="header"><div class="header-inner wrap"><a class="brand" href="{route('index',l)}" aria-label="IT Department"><img src="assets/brand/logo-{variant}.png" width="480" height="232" alt="IT Department"></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" aria-label="{t['menu']}"><span></span><span></span><span></span></button><nav id="main-nav" aria-label="{t['menu']}"><div class="nav-links">{nav}</div><div class="languages" aria-label="{t['lang']}">{langs}</div><a class="button nav-cta" href="{route('contact',l)}">{t['talk']}{A}</a></nav></div></header>'''
def footer(l,t,page='index'):
 links=''.join(f'<a href="{route(p,l)}">{esc(label)}</a>' for p,label in [(key,dict(zip(PAGES,labels(l)))[key]) for key in NAV_ORDER])
 social=[('Instagram','https://www.instagram.com/it.department_'),('LinkedIn','https://www.linkedin.com/company/itdks/'),('Facebook','https://www.facebook.com/share/1QrocF1oGy/?mibextid=wwXIfr')]
 variant={'creative':'creative','ai-agents':'ai'}.get(page,'original')
 return f'''<footer class="footer"><div class="wrap"><div class="footer-top"><a class="brand" href="{route('index',l)}"><img src="assets/brand/logo-{variant}.png" width="480" height="232" alt="IT Department"></a><p>{t['footer']}</p><a class="footer-email" href="mailto:{cfg['email']}">{cfg['email']}{A}</a></div><nav class="footer-nav">{links}</nav><div class="footer-bottom"><span>© 2026 IT Department · {t['location']}</span><div>{''.join(f'<a href="{url}" target="_blank" rel="noopener noreferrer">{name}{A}</a>' for name,url in social)}</div><div><a href="{route('privacy',l)}">{t['privacy']}</a><a href="{route('terms',l)}">{t['terms']}</a></div></div></div></footer>'''
def ending(l,t):
 return f'<section class="wrap end-section"><div class="end-card"><div><p class="eyebrow">{t["talk"]}</p><h2>{copy(l)["contact"]}</h2><p>{t["endingbody"]}</p></div><div class="actions">{button(t["contact"],route("contact",l))}{button("WhatsApp",wa(l),style="outline")}</div></div></section>'
def wa(l): return 'https://wa.me/'+cfg['phoneDigits']+'?text='+quote(tr(l,'Përshëndetje IT Department, dëshiroj të flasim për një projekt.','Hello IT Department, I would like to discuss a project.','Hallo IT Department, ich möchte ein Projekt besprechen.'))
def filters(group,items,l):
 return '<div class="filters" data-filter-group="'+group+'" aria-label="'+esc(tr(l,'Filtro përmbajtjen','Filter content','Inhalte filtern'))+'">'+''.join(f'<button type="button" data-filter="{key}" aria-pressed="{str(i==0).lower()}">{esc(label)}</button>' for i,(key,label) in enumerate(items))+'</div><p class="sr-only filter-status" aria-live="polite" data-filter-status="'+group+'"></p>'
def steps(l,t,names=None):
 c=copy(l); names=names or c['stepnames']
 return '<div class="steps">'+''.join(f'<article><span>0{i+1}</span><h3>{esc(name)}</h3><p>{esc(c["stepdesc"][i]) if i<len(c["stepdesc"]) else ""}</p></article>' for i,name in enumerate(names))+'</div>'
def process(l,t): return '<section class="wrap section">'+heading(t['process'],t['processHeading'])+steps(l,t)+'</section>'
def families(l,t):
 c=copy(l); c['familydesc']=tr(l,['Prezencë dhe procese.','Sisteme që mbajnë.','Rutina më të lehta.','Markë e qartë.'],['Presence and processes.','Systems you rely on.','Lighter routines.','A clearer brand.'],['Auftritt und Abläufe.','Systeme, die tragen.','Leichtere Routinen.','Eine klare Marke.']); dest=[route('services',l)+'#web',route('services',l)+'#it',route('ai-agents',l),route('creative',l)]
 return '<div class="family-grid">'+''.join(f'<a class="family-card card" href="{dest[i]}">{icon(i)}<h3>{esc(name)}</h3><p>{c["familydesc"][i]}</p><span class="card-arrow" aria-hidden="true">↗</span></a>' for i,name in enumerate(c['families']))+'</div>'
def pricing(l,t):
 cards=''
 for i,n in enumerate(source('index',l).find('article','pricing-card')):
  name=first(n,'p','kicker'); price=[99,299,779][i]
  cards+=f'<article class="price-card card"><p class="eyebrow">{esc(name)}</p><h3>{esc(first(n,"h3"))}</h3><p class="price">€{price}<span>{t["month"]}</span></p><details><summary>{t["more"]}<span aria-hidden="true">+</span></summary><ul>'+''.join(f'<li>{esc(li.text())}</li>' for li in n.find('li'))+f'</ul></details>{button(t["enquire"],route("contact",l)+"?service="+quote(name+" €"+str(price)),style="outline")}</article>'
 return '<section class="wrap section" id="packages">'+heading('IT SUPPORT',t['packages'],t['packagenote'])+'<div class="grid three">'+cards+'</div></section>'
def visual_case(l,t,featured=False):
 c=copy(l)
 return f'<article class="case-card {"featured" if featured else ""}" data-filter-item="projects" data-category="software ai"><div class="case-copy"><p class="eyebrow">{c["casebadge"]}</p><h3>{c["casetitle"]}</h3><p>{tr(l,"Nga kërkesa dhe dokumentet te aprovimi — në një rrjedhë të vetme.","From requests and documents to approval — in one connected flow.","Von Anfragen und Dokumenten zur Freigabe — in einem Ablauf.")}</p><a class="text-link" href="{route("project-detail",l)}">{c["details"]}{A}</a></div><div class="workflow-art" aria-label="{esc(c["casebadge"])}"><div class="mock-bar"><i></i><i></i><i></i><span>WORKFLOW</span></div><div class="flow-columns">'+''.join(f'<div><span>{esc(label)}</span><b></b><b></b><b></b></div>' for label in tr(l,['Kërkesa','Në punë','Aprovimi'],['Requests','In progress','Approval'],['Anfragen','In Arbeit','Freigabe']))+'</div><div class="mock-bottom"><span></span><span></span><span></span></div></div></article>'
def brandbook(key,l,t):
 name=key.upper()
 return f'<a class="brandbook card" href="assets/creative/{key}-brandbook.webp" data-lightbox="{name}" data-filter-item="projects" data-category="creative"><div class="book-image {key}"><img src="assets/creative/{key}-brandbook.webp" width="1024" height="1536" loading="lazy" alt="{name} — {t["concept"]}"><span class="image-arrow" aria-hidden="true">↗</span></div><div class="book-caption"><div><p class="eyebrow">{t["concept"]}</p><h3>{name}</h3></div>{A}</div></a>'
def home(l,t):
 c=copy(l)
 hero=f'''<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="red-dot"></span>WEB / SOFTWARE / AI / IT</p><h1>{c['home']}</h1><p class="lead">{c['homelead']}</p><div class="actions">{button(c['see'],route('services',l))}{button(c['book'],cfg['bookingUrl'],'target="_blank" rel="noopener noreferrer"','dark')}</div><div class="hero-proof"><div><strong>140<span>+</span></strong><span>{tr(l,'projekte','projects','Projekte')}</span></div><div><strong>40<span>+</span></strong><span>{tr(l,'klientë','clients','Kunden')}</span></div><p>{t['location']}<br>{t['eyebrow']}</p></div></div><div class="hero-art"><p class="eyebrow">IT DEPARTMENT</p><h2>{c['flow']}</h2><div class="hero-flow">{''.join(f'<div><span>0{i+1}</span><strong>{name}</strong></div>' for i,name in enumerate(c['flowsteps']))}</div><p class="art-foot">{tr(l,'Një ekip. Nga ideja te mbështetja.','One team. From idea to ongoing support.','Ein Team. Von der Idee bis zur Betreuung.')}</p></div></section>'''
 return hero+f'<section class="wrap pillars">{families(l,t)}</section><section class="wrap section">'+heading(t['work'],c['selected'],action=f'<a class="text-link" href="{route("projects",l)}">{t["allwork"]}{A}</a>')+'<div class="selected-grid">'+visual_case(l,t,True)+brandbook('nexus',l,t)+'</div></section>'+partner_rows(l,t,True)+pricing(l,t)+ending(l,t)
def services(l,t):
 c=copy(l); nodes=source('services',l).find('article','service-card'); blocks=''
 for i,(cat,idx) in enumerate([('web',[0,1,2]),('it',[3,4,5]),('ai',[]),('creative',[6,7])]):
  items=''.join(detail(nodes[j],j+1,l,t) for j in idx)
  if cat in ['ai','creative']: items+=button(c['details'],route('ai-agents' if cat=='ai' else 'creative',l),style='outline')
  blocks+=f'<article class="service-family card" id="{cat}" data-filter-item="services" data-category="{cat}"><div class="service-family-title">{icon(i)}<span class="eyebrow">{["01 / 03","04 / 06","AI","07 / 08"][i]}</span><h2>{c["families"][i]}</h2><p>{c["familydesc"][i]}</p></div><div>{items}</div></article>'
 return intro(c['services'],t['servicelead'],t,labels(l)[1])+'<section class="wrap">'+filters('services',[('all',c['all'])]+list(zip(['web','it','ai','creative'],c['families'])),l)+'<div class="grid two service-families">'+blocks+'</div></section>'+pricing(l,t)+process(l,t)+ending(l,t)
def projects(l,t):
 c=copy(l); names=tr(l,['Web','Softuer','IT & siguri','AI','Kreativa'],['Web','Software','IT & security','AI','Creative'],['Web','Software','IT & Sicherheit','KI','Kreativ']); items=visual_case(l,t,True)
 for i,n in enumerate(source('projects',l).find('article','service-card')):
  category=['it','software','it','ai'][i]; title=first(n,'h3'); body=''.join(f'<p>{esc(p)}</p>' for p in paragraphs(n))
  items+=f'<article class="project-tile card" data-filter-item="projects" data-category="{category}"><div class="project-diagram diagram-{i}" aria-hidden="true">{icon(i)}<span></span><span></span><span></span></div><div class="project-content"><p class="eyebrow">{t["examples"]}</p><h3>{esc(title)}</h3><details><summary>{c["details"]}<span aria-hidden="true">+</span></summary>{body}<ul>'+''.join(f'<li>{esc(li.text())}</li>' for li in n.find('li'))+f'</ul>{button(c["request"],route("contact",l)+"?service="+quote(title),style="outline")}</details></div></article>'
 items+=f'<article class="project-tile card" data-filter-item="projects" data-category="web"><div class="web-art" aria-hidden="true"><div></div><strong>WEB.</strong><span></span><span></span></div><div class="project-content"><p class="eyebrow">{t["examples"]}</p><h3>{tr(l,"Nga vizitori te kërkesa.","From visitor to enquiry.","Vom Besuch zur Anfrage.")}</h3><p>{tr(l,"Një shembull strukture: ofertë e qartë, prova vizuale dhe kontakt pa pengesa.","An example structure: a clear offer, visual evidence and an easy next step.","Eine Beispielstruktur: klares Angebot, sichtbare Arbeit und ein einfacher Kontakt.")}</p><a class="text-link" href="{route("services",l)}#web">{c["see"]}{A}</a></div></article>'
 items+=brandbook('nexus',l,t)+brandbook('hyperlink',l,t)
 chips=['Web','Web App','Windows','Android','iOS','Dashboard','AI','E-commerce','Booking','CRM','POS','Inventory','API','Portal']
 return intro(c['projects'],t['projectsLead'],t,labels(l)[2])+'<section class="wrap">'+filters('projects',[('all',c['all'])]+list(zip(['web','software','it','ai','creative'],names)),l)+f'<p class="section-note">{t["examplesNote"]}</p><div class="projects-grid">{items}</div></section><section class="wrap section">'+heading(tr(l,'KAPACITETET','CAPABILITIES','MÖGLICHKEITEN'),tr(l,'Forma e duhur për punën tënde.','The right shape for your work.','Die passende Form für Ihre Arbeit.'))+'<div class="chips">'+''.join(f'<a href="{route("contact",l)}?service={quote(x)}">{x}{A}</a>' for x in chips)+'</div></section>'+ending(l,t)
def case_detail(l,t):
 c=copy(l)
 parts=tr(l,[('Nevoja','Kërkesat, dokumentet dhe aprovimet janë të shpërndara. Ekipi humb kohë duke kërkuar statusin.'),('Zgjidhja','Një rrjedhë me përgjegjës, dokumente dhe hapa aprovimi të lidhur në një vend.'),('Rezultati i synuar','Status i dukshëm dhe përgjegjësi më e qartë për çdo kërkesë.')],[('The need','Requests, documents and approvals are scattered. The team spends time searching for the status.'),('The solution','One workflow connects owners, documents and approval steps.'),('Intended result','Visible status and clearer responsibility for each request.')],[('Der Bedarf','Anfragen, Dokumente und Freigaben sind verstreut. Das Team muss den aktuellen Stand suchen.'),('Die Lösung','Ein Ablauf verbindet Verantwortliche, Dokumente und Freigabeschritte.'),('Angestrebtes Ergebnis','Sichtbarer Status und klare Verantwortung für jede Anfrage.')])
 return intro(c['casefull'],t['examplesNote'],t,c['casebadge'])+'<section class="wrap">'+visual_case(l,t,True)+'</section><section class="wrap section grid three">'+''.join(f'<article class="card padded"><p class="eyebrow">0{i+1}</p><h2>{a}</h2><p>{b}</p></article>' for i,(a,b) in enumerate(parts))+'</section><section class="wrap section"><div class="before-after"><div><p class="eyebrow">'+tr(l,'PARA · SHEMBULL','BEFORE · EXAMPLE','VORHER · BEISPIEL')+'</p><h2>'+tr(l,'Pjesë të shpërndara.','Scattered pieces.','Verteilte Einzelteile.')+'</h2><p>Email → Dokument → Telefon → Email</p></div><div><p class="eyebrow">'+tr(l,'PAS · RRJEDHË E PROPOZUAR','AFTER · PROPOSED FLOW','NACHHER · VORGESCHLAGENER ABLAUF')+'</p><h2>'+tr(l,'Një rrugë e dukshme.','One visible path.','Ein sichtbarer Weg.')+'</h2><p>'+tr(l,'Kërkesë → Përgjegjës → Aprovim → Raport','Request → Owner → Approval → Report','Anfrage → Zuständigkeit → Freigabe → Bericht')+'</p></div></div></section>'+ending(l,t)
PARTNERS=[('cisco','Cisco',0),('mikrotik','MikroTik',0),('hostinger','Hostinger',0),('imatrix','iMatrix',0),('econnect','eConnect',1),('paysera','Paysera',1),('raiffeisen','Raiffeisen Bank',1),('adobe','Adobe',2),('comtrade','Comtrade',2)]
def partner_rows(l,t,teaser=False):
 c=copy(l); rows=''; groups=tr(l,['Rrjet & hosting','Integrime & pagesa','Mjete & ekosistem'],['Networks & hosting','Integrations & payments','Tools & ecosystem'],['Netzwerk & Hosting','Integrationen & Zahlungen','Werkzeuge & Ökosystem'])
 for i,g in enumerate(groups):
  logos=''.join(f'<a class="partner-logo" href="{route("partners",l) if teaser else ""}#partner-{key}" aria-label="{name}"><img src="assets/partners/{key}.svg" alt="{name}" loading="lazy"></a>' for key,name,group in PARTNERS if group==i)
  rows+=f'<div class="partner-row"><p>{g}</p><div>{logos}</div></div>'
 return '<section class="wrap section partner-section">'+(heading(labels(l)[3],tr(l,'Një ekosistem. Më shumë mundësi.','One ecosystem. More possibilities.','Ein Ökosystem. Mehr Möglichkeiten.'),action=f'<a class="text-link" href="{route("partners",l)}">{c["details"]}{A}</a>') if teaser else '')+rows+'</section>'
def partners(l,t):
 c=copy(l)
 descriptions=tr(l,[('Rrjet që mbështet punën e përditshme.','Planifikim dhe konfigurim rrjeti sipas pajisjeve dhe kërkesave të ekipit.'),('Lidhje me më shumë kontroll.','Rrugëzim, segmentim dhe konfigurim për nevojat e rrjetit.'),('Një bazë për faqen tënde.','Hosting, domain dhe publikim sipas kërkesave të projektit.'),('Infrastrukturë në funksion të biznesit.','Përzgjedhje dhe koordinim i infrastrukturës sipas projektit.'),('Sisteme që mund të komunikojnë.','Vlerësim i mundësive të lidhjes dhe integrimit për procesin tënd.'),('Pagesa si pjesë e rrjedhës.','Planifikim i integrimit të pagesave, sipas llogarisë dhe shërbimeve të miratuara.'),('Nga porosia te pagesa.','Vlerësim i mundësive bankare të pagesës për projektin.'),('Mjete për ide që marrin formë.','Dizajn, përmbajtje dhe materiale kreative në një rrjedhë të qëndrueshme.'),('Teknologji në një ekosistem më të gjerë.','Pajisje dhe zgjidhje të përzgjedhura sipas nevojës konkrete.')],[('A network that supports daily work.','Network planning and configuration around your equipment and team.'),('More control over your connections.','Routing, segmentation and configuration for your network needs.'),('A foundation for your website.','Hosting, domains and publishing around project requirements.'),('Infrastructure for your business.','Infrastructure selection and coordination based on the project.'),('Systems that can communicate.','Assessing connectivity and integration options for your processes.'),('Payments within the workflow.','Planning payment integration around your account and approved services.'),('From order to payment.','Assessing bank payment options for the project.'),('Tools that bring ideas to life.','Design, content and creative assets in a consistent workflow.'),('Technology in a wider ecosystem.','Equipment and solutions selected around specific needs.')],[('Ein Netzwerk für den Arbeitsalltag.','Netzwerkplanung und Konfiguration passend zu Geräten und Team.'),('Verbindungen mit mehr Kontrolle.','Routing, Segmentierung und Konfiguration für Ihren Bedarf.'),('Eine Basis für Ihre Website.','Hosting, Domains und Veröffentlichung passend zum Projekt.'),('Infrastruktur für Ihr Unternehmen.','Auswahl und Koordination der Infrastruktur nach Projektbedarf.'),('Systeme, die kommunizieren können.','Prüfung der Verbindungs- und Integrationsmöglichkeiten für Ihre Abläufe.'),('Zahlungen als Teil des Ablaufs.','Planung der Zahlungsintegration nach Konto und freigegebenen Diensten.'),('Von der Bestellung zur Zahlung.','Prüfung der Bank-Zahlungsmöglichkeiten für Ihr Projekt.'),('Werkzeuge für greifbare Ideen.','Design, Inhalte und Kreativmaterial in einem einheitlichen Ablauf.'),('Technologie im größeren Ökosystem.','Geräte und Lösungen nach konkretem Bedarf.')])
 profiles=''
 for i,(key,name,g) in enumerate(PARTNERS):
  title,desc=descriptions[i]; service=['it','web','creative'][g]
  profiles+=f'<details class="partner-profile" id="partner-{key}"><summary><span>{name}</span><span class="profile-title">{title}</span><span aria-hidden="true">+</span></summary><div class="profile-body"><p class="eyebrow">{tr(l,"PROFIL TEKNOLOGJIE","TECHNOLOGY PROFILE","TECHNOLOGIEPROFIL")}</p><h2>{title}</h2><p>{desc}</p><p>{tr(l,"Përfshirja konkrete, qasjet dhe miratimet e ofruesit përcaktohen gjatë analizës së projektit.","The exact scope, access and provider approvals are established during project planning.","Umfang, Zugänge und Anbieterfreigaben werden in der Projektplanung festgelegt.")}</p><div class="actions">{button(c["request"],route("contact",l)+"?service="+quote(name))}<a class="text-link" href="{route("services",l)}#{service}">{c["see"]}{A}</a></div></div></details>'
 note=tr(l,'Platformat e paraqitura janë pjesë e ekosistemit teknologjik. Listimi nuk nënkupton certifikim apo status zyrtar partneri.','These platforms form part of the technology ecosystem. Listing does not imply certification or official partner status.','Diese Plattformen gehören zum Technologie-Ökosystem. Die Nennung bedeutet keine Zertifizierung oder offiziellen Partnerstatus.')
 return intro(c['partners'],c['partnerlead'],t,labels(l)[3])+partner_rows(l,t)+f'<section class="wrap section partner-profiles"><p class="section-note">{note}</p>{profiles}</section>'+ending(l,t)
def enquiry_form(l,t,kind='contact'):
 c=copy(l); options=c['families']+['KrakenOS','Starter €99','Business €299','Enterprise €779']
 if kind=='creative': options=['Branding','Social Media','Video & Motion',tr(l,'Fushatë','Campaign','Kampagne')]
 if kind=='ai': options=['Ari','Dita','Nora','Leo','Mira','Fin']
 options=''.join(f'<option>{esc(x)}</option>' for x in options)
 return f'''<form class="enquiry-form" data-form="{kind}" action="{esc(cfg['formEndpoint'])}" method="post"><input type="hidden" name="source" value="IT Department / {kind} / {l}"><div class="form-row"><label>{t['name']}<input name="name" autocomplete="name" required maxlength="100"></label><label>{t['email']}<input name="email" type="email" autocomplete="email" required maxlength="180"></label></div><div class="form-row"><label>{c['company']}<input name="company" autocomplete="organization" maxlength="150"></label><label>{c['phone']}<input name="phone" type="tel" autocomplete="tel" maxlength="60"></label></div><label>{'AI Agent' if kind=='ai' else t['interest']}<select name="service"><option value="">{t['choose']}</option>{options}</select></label><label>{t['message']}<textarea name="message" rows="4" required maxlength="3000" placeholder="{t['placeholder']}"></textarea></label><p class="form-note">{c['formnote']} <a href="{route('privacy',l)}">{t['privacy']}{A}</a></p><div class="form-submit"><button class="button" type="submit">{c['send']}{A}</button><p class="form-status" role="status" aria-live="polite" tabindex="-1"></p></div><div class="form-recovery" hidden><a class="text-link" href="mailto:{cfg['email']}">{cfg['email']}{A}</a><a class="text-link" href="{wa(l)}">WhatsApp{A}</a></div></form>'''
def brief(l,t,kind,title,desc):
 return f'<section class="wrap section brief-section" id="brief"><div><p class="eyebrow">{tr(l,"HAPI I PARË","THE FIRST STEP","DER ERSTE SCHRITT")}</p><h2>{title}</h2><p>{desc}</p><a class="text-link" href="mailto:{cfg["email"]}">{cfg["email"]}{A}</a></div><div class="form-card">{enquiry_form(l,t,kind)}</div></section>'
def creative(l,t):
 c=copy(l); title=tr(l,['Ide që duken.','Mesazhe që mbeten.'],['Ideas you see.','Messages that stay.'],['Ideen, die auffallen.','Botschaften, die bleiben.'])
 hero=f'<section class="creative-hero wrap"><div><p class="eyebrow">IT DEPARTMENT / CREATIVE STUDIO</p><h1>{title[0]}<br><span>{title[1]}</span></h1><p class="lead">{t["creativeLead"]}</p><div class="actions">{button(tr(l,"Shiko portofolin","View portfolio","Portfolio ansehen"),'#portfolio')}{button(t["talk"],'#brief',style='outline')}</div><div class="creative-tags"><span>Branding</span><span>Social</span><span>Video & Motion</span><span>{tr(l,"Fushata","Campaigns","Kampagnen")}</span></div></div><div class="creative-books"><a href="assets/creative/nexus-brandbook.webp" data-lightbox="NEXUS"><img src="assets/creative/nexus-brandbook.webp" width="1024" height="1536" alt="NEXUS — {t["concept"]}"></a><a href="assets/creative/hyperlink-brandbook.webp" data-lightbox="HYPERLINK"><img src="assets/creative/hyperlink-brandbook.webp" width="1024" height="1536" alt="HYPERLINK — {t["concept"]}"></a><p>{t["concept"]} · NEXUS / HYPERLINK</p></div></section>'
 offerings=''
 for i,n in enumerate(source('creative',l).find('article','creative-service-card')):
  offerings+=f'<article class="card padded"><span class="mini-number">0{i+1}</span><h3>{esc(first(n,"h3"))}</h3>'+''.join(f'<p>{esc(p)}</p>' for p in paragraphs(n)[:1])+f'<a class="text-link" data-creative-service="{esc(first(n,"h3"))}" href="#brief">{t["talk"]}{A}</a></article>'
 portfolio=heading(t['work'],tr(l,'Identitete me karakter.','Identities with character.','Identitäten mit Charakter.'))+filters('portfolio',[('all',c['all']),('nexus','NEXUS'),('hyperlink','HYPERLINK')],l)+'<div class="grid two">'+''.join(brandbook(k,l,t).replace('data-filter-item="projects" data-category="creative"',f'data-filter-item="portfolio" data-category="{k}"') for k in ['nexus','hyperlink'])+'</div>'
 flow=tr(l,['Drejtimi','Dizajni','Lëvizja','Publikimi','Matja'],['Direction','Design','Motion','Publish','Measure'],['Richtung','Design','Bewegung','Veröffentlichen','Messen'])
 return hero+'<section class="wrap section" id="portfolio">'+portfolio+'</section><section class="wrap section">'+heading(labels(l)[4],tr(l,'Nga ideja te materiali i gatshëm.','From the idea to the finished work.','Von der Idee zum fertigen Material.'))+'<div class="grid three">'+offerings+'</div></section><section class="wrap section"><div class="creative-process">'+''.join(f'<div><span>0{i+1}</span><h3>{x}</h3></div>' for i,x in enumerate(flow))+'</div></section><section class="wrap bridge-card"><h2>'+tr(l,'Një gjuhë. Në çdo pikë kontakti.','One language. Every touchpoint.','Eine Sprache. An jedem Kontaktpunkt.')+'</h2><p>'+tr(l,'Identiteti lidhet me faqen, sistemin dhe fushatën. Kështu, marka jote ndihet e njëjtë kudo.','Your identity connects with the website, system and campaign. Your brand feels consistent everywhere.','Ihre Identität verbindet Website, System und Kampagne. So wirkt Ihre Marke überall einheitlich.')+'</p>'+button(c['see'],route('services',l)+'#creative',style='outline')+'</section>'+brief(l,t,'creative',tr(l,'Na trego idenë.','Tell us your idea.','Erzählen Sie uns Ihre Idee.'),tr(l,'Një brief i shkurtër është një fillim i mirë.','A short brief is a good place to start.','Ein kurzes Briefing ist ein guter Anfang.'))
def ai(l,t):
 c=copy(l); title=tr(l,['Zgjidh punën.','Ne lidhim agjentin.'],['Choose the task.','We connect the agent.'],['Wählen Sie die Aufgabe.','Wir verbinden den Agenten.'])
 flow=tr(l,['Kërkesa','Agjenti','Aprovimi','Veprimi'],['Request','Agent','Approval','Action'],['Anfrage','Agent','Freigabe','Aktion'])
 hero=f'<section class="ai-hero wrap"><div><p class="eyebrow"><span class="live-dot"></span>IT DEPARTMENT / AI AGENTS</p><h1>{title[0]}<br><span>{title[1]}</span></h1><p class="lead">{t["aiLead"]}</p><div class="actions">{button(tr(l,"Zgjidh agjentin","Choose an agent","Agenten wählen"),'#agents')}{button(tr(l,"Nis një pilot","Start a pilot","Pilotprojekt starten"),'#brief',style='outline')}</div></div><div class="ai-flow-card"><div class="agent-orbit">{icon(2)}<span>AI</span></div><div class="ai-flow">'+''.join(f'<div><small>0{i+1}</small><strong>{s}</strong></div>' for i,s in enumerate(flow))+'</div><p>'+tr(l,'Rregulla të qarta. Kontroll njerëzor.','Clear rules. Human oversight.','Klare Regeln. Menschliche Kontrolle.')+'</p></div></section>'
 agents=''
 boundaries=tr(l,['Burimet','Veprimet','Aprovimi njerëzor'],['Sources','Actions','Human approval'],['Quellen','Aktionen','Menschliche Freigabe'])
 for i,n in enumerate(source('ai-agents',l).find('article','ai-agent-card')):
  name=['Ari','Dita','Nora','Leo','Mira','Fin'][i]; role=first(n,cls='ai-agent-tag'); ps=paragraphs(n)
  agents+=f'<article class="agent-card card" id="agent-{name.lower()}"><div class="agent-heading"><span class="robot robot-{i}">{icon(2)}</span><span class="agent-index">0{i+1}</span></div><p class="agent-name">{name}</p><h3>{esc(role)}</h3><p>{esc(ps[0]) if ps else ""}</p><details><summary>{c["details"]}<span aria-hidden="true">+</span></summary><div class="agent-details"><h4>{boundaries[0]}</h4><p>{tr(l,"Vetëm burimet dhe qasjet e miratuara për pilotin.","Only sources and access approved for the pilot.","Nur für den Pilot genehmigte Quellen und Zugänge.")}</p><h4>{boundaries[1]}</h4><ul>'+''.join(f'<li>{esc(li.text())}</li>' for li in n.find('li'))+f'</ul><h4>{boundaries[2]}</h4><p>{tr(l,"Dërgimet dhe ndryshimet me ndikim kërkojnë rregulla dhe miratim të përcaktuar nga ekipi.","Sending and consequential changes require rules and approval defined by your team.","Versand und folgenreiche Änderungen benötigen Regeln und eine vom Team festgelegte Freigabe.")}</p></div></details><a class="text-link" data-agent="{name}" href="#brief">{tr(l,"Diskuto këtë agjent","Discuss this agent","Diesen Agenten besprechen")}{A}</a></article>'
 pilot=tr(l,['Auditim','Rasti i përdorimit','Pilot','Integrim','Monitorim'],['Audit','Use case','Pilot','Integration','Monitoring'],['Analyse','Anwendungsfall','Pilot','Integration','Monitoring'])
 return hero+'<section class="wrap section" id="agents">'+heading('AI AGENTS',tr(l,'Secili me një rol të qartë.','Each with a clear role.','Jeder mit einer klaren Rolle.'))+'<div class="grid three">'+agents+'</div></section><section class="wrap section"><div class="integration-band"><h2>'+tr(l,'Lidhet me mënyrën si punon.','Connects with how you work.','Verbunden mit Ihren Abläufen.')+'</h2><div class="chips">'+''.join(f'<span>{s}</span>' for s in ['WhatsApp','Email','CRM',tr(l,'Formularë','Forms','Formulare'),tr(l,'Tabela & dokumente','Tables & documents','Tabellen & Dokumente')])+'</div><p>'+tr(l,'Integrimet konfigurohen për çdo projekt, me qasjet dhe miratimet përkatëse.','Integrations are configured per project, with the required access and approvals.','Integrationen werden je Projekt mit den erforderlichen Zugängen und Freigaben eingerichtet.')+'</p></div></section><section class="wrap section"><div class="creative-process">'+''.join(f'<div><span>0{i+1}</span><h3>{s}</h3></div>' for i,s in enumerate(pilot))+'</div></section><section class="wrap guard-card">'+icon(1)+f'<div><h2>{t["aiguard"]}</h2><p>{t["aiguardbody"]}</p></div></section>'+brief(l,t,'ai',tr(l,'Cilën punë ta lehtësojmë?','Which task can we make easier?','Welche Aufgabe können wir erleichtern?'),tr(l,'Zgjedhim një rast të qartë dhe e provojmë me ekipin tënd.','We choose a clear use case and test it with your team.','Wir wählen einen klaren Anwendungsfall und testen ihn mit Ihrem Team.'))
def about(l,t):
 c=copy(l); src=source('about',l); faqs=src.find('details','faq-card'); groups=''
 for i,g in enumerate(c['faqgroups']):
  inner=''.join(f'<details class="faq"><summary>{esc(first(n,cls="faq-question"))}<span aria-hidden="true">+</span></summary><div>{esc(first(n,cls="faq-answer"))}</div></details>' for n in [faqs[j] for j in [[0,2,8,10],[1,5,9],[3,4],[6,7,11]][i]])
  groups+=f'<section class="faq-group" data-filter-item="faq" data-category="{i}"><h3>{g}</h3>{inner}</section>'
 values=tr(l,[('Qartësi','E shpjegojmë çfarë po ndërtojmë, pse dhe çfarë vjen më pas.'),('Përgjegjësi','Përcaktojmë pronësinë, afatet dhe mënyrën si kujdesemi për punën.'),('Bashkëpunim','Punojmë me ekipin tënd, afër nevojës reale të biznesit.')],[('Clarity','We explain what we are building, why and what comes next.'),('Responsibility','We define ownership, timing and how the work will be supported.'),('Collaboration','We work with your team, close to the needs of the business.')],[('Klarheit','Wir erklären, was wir entwickeln, warum und was als Nächstes kommt.'),('Verantwortung','Wir klären Zuständigkeit, Termine und die weitere Betreuung.'),('Zusammenarbeit','Wir arbeiten mit Ihrem Team, nah am tatsächlichen Bedarf.')])
 hero=f'<section class="about-hero wrap"><div><p class="eyebrow">IT DEPARTMENT / {labels(l)[6]}</p><h1>{c["about"]}</h1><p class="lead">{t["aboutLead"]}</p>{button(t["talk"],route("contact",l))}</div><div class="quote-card"><span aria-hidden="true">“</span><h2>{tr(l,"Punë më e qartë. Sisteme më të sigurta.","Clearer work. Safer systems.","Klarere Arbeit. Sicherere Systeme.")}</h2><p>IT Department · {t["location"]}</p></div></section>'
 return hero+'<section class="wrap grid three values">'+''.join(f'<article class="card padded"><p class="eyebrow">0{i+1}</p><h2>{a}</h2><p>{b}</p></article>' for i,(a,b) in enumerate(values))+'</section>'+process(l,t)+'<section class="wrap section"><div class="about-benefits"><h2>'+tr(l,'Për njerëzit pas çdo procesi.','For the people behind every process.','Für die Menschen hinter jedem Ablauf.')+'</h2><p>'+tr(l,'Ekipi, klientët, të dhënat dhe puna e përditshme — të menduara si pjesë të një sistemi.','Your team, customers, data and everyday work — considered as parts of one system.','Team, Kunden, Daten und tägliche Arbeit — als Teile eines Systems gedacht.')+'</p></div></section><section class="wrap section" id="faq">'+heading('FAQ',t['faq'])+filters('faq',[('all',c['all'])]+[(str(i),g) for i,g in enumerate(c['faqgroups'])],l)+groups+'</section>'+ending(l,t)
def contact(l,t):
 c=copy(l); titles=tr(l,['Takim 30-minutësh','WhatsApp','Kërkesë me shkrim'],['30-minute meeting','WhatsApp','Written enquiry'],['30-Minuten-Gespräch','WhatsApp','Schriftliche Anfrage']); desc=tr(l,['Zgjedh orarin që të përshtatet.','Një bisedë e drejtpërdrejtë.','Na jep pak kontekst për nevojën.'],['Choose a time that suits you.','A direct conversation.','Give us some context about your needs.'],['Wählen Sie einen passenden Termin.','Ein direktes Gespräch.','Geben Sie uns etwas Kontext zu Ihrem Bedarf.']); dest=[cfg['bookingUrl'],wa(l),'#enquiry']
 return intro(c['contact'],tr(l,'Zgjidh mënyrën që të përshtatet. Pjesën tjetër e sqarojmë bashkë.','Choose the way that suits you. We’ll work through the rest together.','Wählen Sie den passenden Weg. Alles Weitere klären wir gemeinsam.'),t,t['contact'])+'<section class="wrap grid three contact-paths">'+''.join(f'<a class="card contact-path" href="{esc(dest[i])}"><span class="eyebrow">0{i+1}</span><h2>{title}</h2><p>{desc[i]}</p>{A}</a>' for i,title in enumerate(titles))+f'</section><section class="wrap section contact-grid" id="enquiry"><aside><p class="eyebrow">IT DEPARTMENT</p><h2>{t["write"]}</h2><div class="contact-details"><a href="mailto:{cfg["email"]}">{cfg["email"]}{A}</a><a href="tel:+{cfg["phoneDigits"]}">{cfg["phoneDisplay"]}{A}</a><p>{t["location"]}<br>{t["hours"]}</p></div><a class="map-card" href="https://www.google.com/maps/search/?api=1&amp;query=42.655800066393724%2C21.151119141173435" target="_blank" rel="noopener noreferrer"><span class="map-pin">{icon(1)}</span><strong>{t["location"]}</strong><span>{tr(l,"Hap vendndodhjen orientuese","Open approximate location","Ungefähren Standort öffnen")}{A}</span></a></aside><div class="form-card"><h2>{tr(l,"Na trego pak për projektin.","Tell us about your project.","Erzählen Sie uns von Ihrem Projekt.")}</h2>{enquiry_form(l,t)}</div></section>'
def krakenos(l,t):
 c=copy(l); lead=tr(l,'Një platformë modulare për njerëzit, klientët, financat dhe punën e përditshme. Pjesët lidhen rreth mënyrës si punon kompania jote.','A modular platform for people, customers, finance and daily work. Connected around the way your company operates.','Eine modulare Plattform für Menschen, Kunden, Finanzen und tägliche Arbeit. Verbunden mit den Abläufen Ihres Unternehmens.')
 hero=f'<section class="kraken-hero wrap"><div><p class="eyebrow">IT DEPARTMENT / KRAKENOS</p><h1>Many arms.<br><span>One brain.</span></h1><p class="lead">{lead}</p><div class="actions">{button(tr(l,"Shiko modulet","Explore modules","Module ansehen"),"#modules")}{button(c["demo"],route("contact",l)+"?service=KrakenOS",style="outline")}</div></div><a class="product-hero-image" href="assets/krakenos/dashboard.png" data-lightbox="KrakenOS"><img src="assets/krakenos/dashboard.png" width="894" height="513" alt="KrakenOS — Dashboard"><span>{c["screenshot"]}{A}</span></a></section>'
 modules=tr(l,[('CRM & shitje','Nga kontakti te marrëdhënia me klientin.',['Klientë dhe kontakte','Mundësi dhe ndjekje','Aktivitete dhe histori']),('Workspace','Një vend për njerëzit dhe punën.',['Ekipi dhe detyrat','Projektet dhe afatet','Koordinimi i punës']),('Financa & kontabilitet','Pamje e lidhur e pjesës financiare.',['Fatura dhe shpenzime','Raporte financiare','Të dhëna sipas rolit']),('Dokumente & komunikim','Informacioni pranë procesit.',['Dokumente dhe skedarë','Komunikimi i ekipit','AURA dhe mjete të përbashkëta'])],[('CRM & sales','From first contact to customer relationship.',['Customers and contacts','Opportunities and follow-up','Activity and history']),('Workspace','A place for people and work.',['Team and tasks','Projects and deadlines','Work coordination']),('Finance & accounting','A connected view of finances.',['Invoices and expenses','Financial reports','Role-based information']),('Documents & communication','Information close to the process.',['Documents and files','Team communication','AURA and shared tools'])],[('CRM & Vertrieb','Vom ersten Kontakt zur Kundenbeziehung.',['Kunden und Kontakte','Chancen und Nachverfolgung','Aktivitäten und Verlauf']),('Workspace','Ein Ort für Menschen und Arbeit.',['Team und Aufgaben','Projekte und Termine','Arbeitskoordination']),('Finanzen & Buchhaltung','Ein verbundener Blick auf die Finanzen.',['Rechnungen und Ausgaben','Finanzberichte','Rollenbezogene Informationen']),('Dokumente & Kommunikation','Informationen nah am Ablauf.',['Dokumente und Dateien','Teamkommunikation','AURA und gemeinsame Werkzeuge'])])
 cards=''.join(f'<article class="card padded module-card">{icon(i)}<h3>{title}</h3><p>{desc}</p><details><summary>{c["details"]}<span aria-hidden="true">+</span></summary><ul>'+''.join(f'<li>{esc(x)}</li>' for x in items)+'</ul></details></article>' for i,(title,desc,items) in enumerate(modules))
 gallery=''.join(f'<a class="product-shot card" href="assets/krakenos/{key}.png" data-lightbox="KrakenOS / {label}"><img src="assets/krakenos/{key}.png" width="802" height="644" loading="lazy" alt="KrakenOS — {label}"><div><h3>{label}</h3>{A}</div></a>' for key,label in [('overview',tr(l,'Përmbledhje','Overview','Übersicht')),('workspace','Workspace'),('finance',tr(l,'Financat','Finance','Finanzen'))])
 return hero+'<section class="wrap section" id="modules">'+heading('KRAKENOS',tr(l,'Një sistem. Pjesët që të duhen.','One system. The parts you need.','Ein System. Die Teile, die Sie brauchen.'))+'<div class="grid four">'+cards+'</div></section><section class="wrap section"><div class="kraken-special"><div><p class="eyebrow">'+tr(l,'SIPAS BIZNESIT','BUILT AROUND YOUR BUSINESS','PASSEND ZUM UNTERNEHMEN')+'</p><h2>'+tr(l,'Hapësirë për mënyrën tënde të punës.','Room for the way you work.','Raum für Ihre Arbeitsweise.')+'</h2></div><div><div class="chips"><a href="'+route('contact',l)+'?service=KrakenOS%20PMS">PMS ↗</a><a href="'+route('contact',l)+'?service=KrakenOS%20Medical">Medical ↗</a><a href="'+route('contact',l)+'?service=KrakenOS%20Hospitality">Hospitality ↗</a></div><p>'+tr(l,'Modulet, administrimi, rolet dhe përshtatjet sektoriale përcaktohen sipas projektit dhe verifikohen në demo.','Modules, administration, roles and sector-specific adaptations are scoped per project and reviewed in the demo.','Module, Verwaltung, Rollen und branchenspezifische Anpassungen werden je Projekt festgelegt und in der Demo geprüft.')+'</p></div></div></section><section class="wrap section">'+heading(c['screenshot'],tr(l,'Shiko si lidhen pjesët.','See how the pieces connect.','So greifen die Teile ineinander.'))+'<div class="grid three">'+gallery+'</div></section><section class="wrap section"><div class="kraken-cta"><h2>'+tr(l,'Ta shohim në kontekstin tënd.','Let’s see it in your context.','Sehen wir es in Ihrem Kontext.')+'</h2><p>'+tr(l,'Na trego ekipin dhe procesin. E nisim demonstrimin nga ajo që ka rëndësi për ty.','Tell us about the team and process. We’ll start the demonstration with what matters to you.','Beschreiben Sie Team und Ablauf. Wir beginnen die Demo mit dem, was für Sie zählt.')+'</p>'+button(c['demo'],route('contact',l)+'?service=KrakenOS')+'</div></section>'

builders={"index":home,"services":services,"projects":projects,"partners":partners,"creative":creative,"ai-agents":ai,"about":about,"contact":contact,"krakenos":krakenos,"project-detail":case_detail,"terms":terms}
for l,t in T.items():
 c=copy(l)
 for page in [*builders,'privacy','404']:
  if page in builders: body=builders[page](l,t)
  elif page=='privacy': body=intro(t['privacyTitle'],'',t)+f'<div class="wrap legal"><p>{c["privacy"]}</p><a class="text-link" href="mailto:{cfg["email"]}">{cfg["email"]}{A}</a></div>'
  else: body=intro(t['notfound'],t['notfoundbody'],t,'404')+f'<div class="wrap error-back">{button(t["back"],route("index",l))}</div>'
  title=dict(zip(PAGES,labels(l))).get(page,{'project-detail':c['casefull'],'privacy':t['privacy'],'terms':t['terms'],'404':'404'}.get(page,''))
  if page=='index': title=c['home']
  description={'index':c['homelead'],'services':t['servicelead'],'projects':t['projectsLead'],'partners':c['partnerlead'],'creative':t['creativeLead'],'ai-agents':t['aiLead'],'about':t['aboutLead'],'contact':c['contact'],'krakenos':tr(l,'Një platformë modulare për kompaninë tuaj.','A modular platform for your company.','Eine modulare Plattform für Ihr Unternehmen.'),'project-detail':t['examplesNote'],'privacy':t['privacyTitle'],'terms':t['terms'],'404':t['notfoundbody']}[page]
  data=json.dumps({**{k:c[k] for k in ['send','sending','success','failure','invalid','count']},'close':t['close']},ensure_ascii=False).replace('<','\\u003c')
  alternates=''.join(f'<link rel="alternate" hreflang="{lang}" href="{route(page,lang)}">' for lang in ['sq','en','de'])
  html=f'''<!doctype html><html lang="{l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | IT Department</title><meta name="description" content="{esc(description)}"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#17181a"><link rel="icon" href="assets/brand/favicon.png">{alternates}<link rel="stylesheet" href="assets/site.css"><script type="application/json" id="site-copy">{data}</script><script src="assets/site.js" defer></script></head><body data-page="{page}">{header(page,l,t)}<main id="main">{body}</main>{footer(l,t,page)}<dialog class="lightbox" id="lightbox" aria-labelledby="lightbox-title"><div class="lightbox-toolbar"><strong id="lightbox-title"></strong><button class="lightbox-close" type="button">{t['close']}<span aria-hidden="true">×</span></button></div><img id="lightbox-image" alt=""></dialog></body></html>'''
  (OUT/route(page,l)).write_text(html,encoding='utf-8')
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n',encoding='utf-8')
print('Generated 39 pages from the supplied proposal in SQ, EN and DE.')
