import {chromium} from 'file:///C:/Users/A/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];const check=(n,v)=>{assert(v,n);results.push(n);};
for(const lang of ['sq','en','de'])for(const width of [1440,390]){
 const ctx=await browser.newContext({viewport:{width,height:850}});const p=await ctx.newPage();let widgets=0;
 await p.route('https://assets.calendly.com/**',r=>{widgets++;return r.fulfill({contentType:'application/javascript',body:'window.Calendly={initInlineWidget({url,parentElement}){const f=document.createElement("iframe");f.src=url;parentElement.append(f);}};'});});
 await p.route('https://calendly.com/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><title>Intercepted booking fixture</title><button id="confirm">Simulated confirmation for local test only</button><script>parent.postMessage({event:"calendly.event_type_viewed"},"*");document.querySelector("button").onclick=()=>parent.postMessage({event:"calendly.event_scheduled",payload:{event:{uri:"https://api.calendly.com/scheduled_events/local-qa"},invitee:{email:"private@example.invalid"}}},"*");</script>'}));
 await p.goto('http://127.0.0.1:8791/index'+(lang==='sq'?'':'-'+lang)+'.html');await p.evaluate(()=>{window.events=[];document.addEventListener('itd:measurement',e=>events.push(e.detail));});check(lang+width+' no unsolicited widget',widgets===0);const link=p.locator('.hero a[href*="calendly.com"]');await link.click();await p.frameLocator('.booking-host iframe').locator('#confirm').waitFor();check(lang+width+' dialog opens',await p.locator('.booking-dialog').evaluate(e=>e.open));check(lang+width+' click not conversion',await p.evaluate(()=>events.length===0));check(lang+width+' body locked',await p.evaluate(()=>getComputedStyle(document.body).overflow==='hidden'));
 await p.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{origin:'https://calendly.com',source:window,data:{event:'calendly.event_scheduled',payload:{event:{uri:'https://api.calendly.com/scheduled_events/forged'}}}})));check(lang+width+' wrong source rejected',await p.evaluate(()=>events.length===0));
 await p.frameLocator('.booking-host iframe').locator('#confirm').click();await p.waitForFunction(()=>events.length===1);check(lang+width+' confirmed booking event',await p.evaluate(()=>events[0].name==='book_meeting'));check(lang+width+' no invitee data',!(await p.evaluate(()=>JSON.stringify(events))).includes('@'));
 await p.frameLocator('.booking-host iframe').locator('#confirm').click();check(lang+width+' duplicate suppressed',await p.evaluate(()=>events.length===1));await p.locator('.booking-toolbar button').click();check(lang+width+' focus restored',await link.evaluate(e=>e===document.activeElement));await link.click();check(lang+width+' calendar retained',widgets===1&&await p.locator('.booking-host iframe').count()===1);await p.locator('.booking-toolbar button').focus();await p.keyboard.press('Escape');check(lang+width+' Escape closes',await p.locator('.booking-dialog').evaluate(e=>!e.open));await ctx.close();
}
const ctx=await browser.newContext(),p=await ctx.newPage();await p.route('https://assets.calendly.com/**',r=>r.abort());await p.goto('http://127.0.0.1:8791/index-en.html');await p.locator('.hero a[href*="calendly.com"]').click();await p.waitForFunction(()=>document.querySelector('.booking-status').textContent.includes('does not open'));check('provider unavailable fallback',await p.locator('.booking-fallback').getAttribute('href')==='https://calendly.com/arion-gjonbalaj/30min');
await writeFile('alternative-v2/qa/proposal/booking-report.json',JSON.stringify({checks:results.length,results,provider:'Intercepted widget and booking confirmations. No real bookings made.'},null,2));console.log(JSON.stringify({checks:results.length,realBookings:0}));await browser.close();
