def home(l,t):
 custom={
 "sq":{"title":["Puna jote.","Më e lehtë."],"label":"TEKNOLOGJI ME NJË QËLLIM TË QARTË","explore":"Gjej pikën tënde të nisjes","tabs":["Prezencë","Organizim","Mbështetje"],"panel":["Një prezencë që punon për ty.","Një vend për gjithë punën.","Një bazë ku mund të mbështetesh."],"diagram":[["Ide","Identitet","Kontakt"],["Klientë","Procese","Raporte"],["Qasje","Siguri","Backup"]],"link":"Zbulo zgjidhjet","sculpture":"Skulpturë e mburojës së IT Department","small":"PJESËT E DUHURA. TË LIDHURA MIRË.","start":"ZGJIDH PIKËN E NISJES"},
 "en":{"title":["Your business.","In good hands."],"label":"TECHNOLOGY WITH A CLEAR PURPOSE","explore":"Find your starting point","tabs":["Presence","Organization","Support"],"panel":["A presence that works for you.","One place for the way you work.","A foundation you can rely on."],"diagram":[["Idea","Identity","Contact"],["Clients","Processes","Reports"],["Access","Security","Backup"]],"link":"Explore the solutions","sculpture":"Sculptural IT Department shield","small":"THE RIGHT PIECES. WELL CONNECTED.","start":"CHOOSE YOUR STARTING POINT"},
 "de":{"title":["Ihr Business.","In guten Händen."],"label":"TECHNOLOGIE MIT EINEM KLAREN ZIEL","explore":"Finden Sie Ihren Ausgangspunkt","tabs":["Auftritt","Organisation","Support"],"panel":["Ein Auftritt, der für Sie arbeitet.","Ein Ort für Ihre Arbeitsabläufe.","Eine Basis, auf die Sie bauen können."],"diagram":[["Idee","Identität","Kontakt"],["Kunden","Prozesse","Berichte"],["Zugang","Sicherheit","Backup"]],"link":"Lösungen entdecken","sculpture":"Skulptur des IT Department Schildes","small":"DIE RICHTIGEN BAUSTEINE. GUT VERBUNDEN.","start":"WÄHLEN SIE IHREN AUSGANGSPUNKT"}
 }[l]
 tabs="";panels=""
 for i,(group,anchor) in enumerate(zip(t["groups"],["presence","operations","support"])):
  tabs+=f'<button class="need-tab" id="need-tab-{i}" role="tab" aria-controls="need-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}"><span class="need-tab-number">0{i+1}</span><span><strong>{group[0]}</strong><small>{group[2]}</small></span><span class="need-tab-arrow" aria-hidden="true">↗</span></button>'
  diagram=custom["diagram"][i]
  if i==0:
   drawing=f'<div class="design-board" aria-hidden="true"><div class="board-top"><span>ITD / STUDIO</span><span>01—03</span></div><div class="board-type">Aa<span>↗</span></div><div class="board-bottom"><div class="swatches"><i></i><i></i><i></i></div><span>{diagram[0]}<b> / </b>{diagram[1]}<b> / </b>{diagram[2]}</span></div></div>'
  elif i==1:
   drawing=f'<div class="system-board" aria-hidden="true"><span class="diagram-caption">ITD / SYSTEMS</span><div class="system-nodes"><div><span>01</span><strong>{diagram[0]}</strong></div><i>→</i><div class="node-main"><span>02</span><strong>{diagram[1]}</strong></div><i>→</i><div><span>03</span><strong>{diagram[2]}</strong></div></div><div class="system-line"></div></div>'
  else:
   drawing=f'<div class="support-board" aria-hidden="true"><span class="diagram-caption">ITD / SUPPORT</span><div class="support-orbit"></div><img src="assets/brand/logo-shield.png" width="70" height="70" alt=""><span class="support-label first">{diagram[0]}</span><span class="support-label second">{diagram[1]}</span><span class="support-label third">{diagram[2]}</span></div>'
  panels+=f'<section class="need-panel" id="need-panel-{i}" role="tabpanel" aria-labelledby="need-tab-{i}" tabindex="0" {"" if i==0 else "hidden"}><div class="need-panel-drawing">{drawing}</div><div class="need-panel-copy"><h3>{custom["panel"][i]}</h3><p>{group[1]}</p><a class="text-link" href="{route("services",l)}#{anchor}">{custom["link"]}{A}</a></div></section>'
 art=f'<div class="signature-art"><span class="art-edition">ITD—01 / {t["location"]}</span><div class="sculpture-stage"><div class="sculpture-ring"></div><img class="shield-sculpture" src="assets/brand/shield-sculpture.png" width="1254" height="1254" fetchpriority="high" alt="{custom["sculpture"]}"></div><div class="art-baseline"><span class="red-dot"></span><span>{custom["small"]}</span><span aria-hidden="true">↗</span></div></div>'
 return f'''<section class="hero signature-hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="red-dot"></span>{custom["label"]}</p><h1>{custom["title"][0]}<br><em>{custom["title"][1]}</em></h1><p class="intro">{t["intro"]}</p>{button(t["cta"],route("contact",l))}<a class="hero-secondary" href="#solutions">{custom["explore"]}<span aria-hidden="true">↓</span></a><p class="hero-note">{t["note"]}</p></div>{art}</section><div class="location-strip wrap"><span>{t["location"]}</span><span>Web & Software<span class="strip-dot">·</span>IT & Security<span class="strip-dot">·</span>AI & Creative</span><span class="strip-end">IT Department / 2026</span></div><section class="needs-section wrap" id="solutions"><div class="section-heading"><div><p class="eyebrow">{custom["start"]}</p><h2>{t["serviceHeading"]}</h2></div><p>{t["serviceIntro"]}</p></div><div class="needs-explorer"><div class="need-tabs" role="tablist" aria-label="{t["services"]}" aria-orientation="vertical">{tabs}</div><div class="need-panels">{panels}</div></div></section>{work(l,t,True)}{process(l,t)}{ending(l,t)}'''

