def header(page,l,t):
 nav="".join(f'<a href="{route(p,l)}" '+('aria-current="page"' if p==page else '')+f'>{esc(label)}</a>' for p,label in zip(["services","projects","about"],t["nav"]))
 langs="".join(f'<a href="{route(page,x)}" lang="{x}" aria-label="{name}" '+('aria-current="true"' if x==l else '')+f'>{x.upper()}</a>' for x,name in [("sq","Shqip"),("en","English"),("de","Deutsch")])
 return f'''<a class="skip" href="#main">{t["skip"]}</a><header class="header"><div class="wrap header-inner"><a class="brand" href="{route("index",l)}" aria-label="IT Department"><img src="assets/brand/logo-original.png" width="480" height="232" alt="IT Department"></a><nav class="desktop-nav" aria-label="{t["menu"]}">{nav}</nav><div class="header-actions"><nav class="languages" aria-label="{t["lang"]}">{langs}</nav><a class="header-cta" href="{route("contact",l)}">{t["talk"]}{A}</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav" aria-label="{t["menu"]}"><span class="menu-lines" aria-hidden="true"></span></button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="{t["menu"]}" hidden>{nav}<a href="{route("contact",l)}">{t["contact"]}</a></nav></header>'''

def footer(l,t):
 links="".join(f'<a href="{route(p,l)}">{esc(label)}</a>' for p,label in [("services",t["nav"][0]),("projects",t["nav"][1]),("about",t["nav"][2]),("creative","Kreativa" if l=="sq" else "Creative"),("ai-agents","AI Agents" if l!="de" else "KI-Agenten"),("contact",t["contact"])])
 return f'''<footer class="footer"><div class="wrap"><div class="footer-top"><a class="brand" href="{route("index",l)}"><img src="assets/brand/logo-original.png" width="480" height="232" alt="IT Department"></a><p>{t["footer"]}</p><a href="mailto:{cfg["email"]}">{cfg["email"]}{A}</a></div><div class="footer-mid"><nav>{links}</nav><div><a href="https://www.instagram.com/it.department_" target="_blank" rel="noopener noreferrer">Instagram {A}</a><a href="https://www.linkedin.com/company/itdks/" target="_blank" rel="noopener noreferrer">LinkedIn {A}</a></div></div><div class="footer-bottom"><span>© 2026 IT Department · {t["location"]}</span><nav><a href="{route("privacy",l)}">{t["privacy"]}</a><a href="{route("terms",l)}">{t["terms"]}</a></nav></div></div></footer>'''

def ending(l,t):
 c={"sq":["Ke një ide?","Ta bëjmë bashkë.","Nga një bisedë e thjeshtë mund të fillojë diçka e madhe."],"en":["Have an idea?","Let’s make it happen.","A simple conversation can be the start of something bigger."],"de":["Eine Idee?","Machen wir sie wahr.","Ein einfaches Gespräch kann der Anfang von etwas Großem sein."]}[l]
 return f'<section class="ending-band"><div class="ending wrap"><div><p class="eyebrow">{t["talk"]}</p><h2>{c[0]}<br><span>{c[1]}</span></h2><p>{c[2]}</p></div><a class="ending-link" href="{route("contact",l)}"><span class="ending-arrow" aria-hidden="true">↗</span><span>{t["talk"]}</span></a></div></section>'

def intro(title,desc,t,kicker="IT DEPARTMENT"):
 return f'<section class="page-intro wrap"><p class="eyebrow"><span class="red-dot"></span>{esc(kicker)}</p><h1>{esc(title)}</h1><p class="intro">{esc(desc)}</p></section>'

def work(l,t,home=False):
 cards=""
 for i,(key,label) in enumerate([("nexus","NEXUS"),("hyperlink","HYPERLINK")]):
  cards+=f'<a class="work-card" href="assets/creative/{key}-brandbook.webp" data-lightbox="{label}" aria-label="{t["view"]}: {label}"><div class="work-image work-{key}"><div class="work-image-top"><span>{label}</span><span class="work-tag">{t["concept"]}</span></div><img src="assets/creative/{key}-brandbook.webp" width="1024" height="1536" loading="lazy" alt="{label} — {t["concept"]}"><span class="work-open" aria-hidden="true">↗</span></div><div class="work-caption"><h3>{label}</h3><p>Branding / Art direction</p></div></a>'
 c={"sq":["Pak nga imagjinata jonë.","Identitete që dallohen."],"en":["A little of our imagination.","Identities that stand out."],"de":["Ein Einblick in unsere Ideen.","Identitäten, die auffallen."]}[l]
 more=f'<a class="text-link" href="{route("projects",l)}">{t["allwork"]}{A}</a>' if home else ""
 return f'<section class="work-section wrap" id="selected-work"><div class="section-heading"><div><p class="eyebrow">{t["work"]}</p><h2>{c[0]}</h2></div>{more}</div><div class="work-grid">{cards}</div></section>'

def process(l,t):
 c={"sq":["Një ekip.","Shumë mënyra për të ecur përpara.","Dizajni, zhvillimi dhe IT-ja funksionojnë më mirë kur mendojnë bashkë."],"en":["One team.","More ways to move forward.","Design, development and IT work better when they think together."],"de":["Ein Team.","Mehr Wege nach vorne.","Design, Entwicklung und IT funktionieren besser, wenn sie gemeinsam denken."]}[l]
 steps="".join(f'<article><span class="step-number">0{i+1}</span><div><h3>{s[0]}</h3><p>{s[1]}</p></div></article>' for i,s in enumerate(t["steps"]))
 return f'<section class="process-section"><div class="wrap"><div class="process-intro"><p class="eyebrow">{t["process"]}</p><h2>{c[0]}<br><span>{c[1]}</span></h2><div><p>{c[2]}</p><a class="text-link" href="{route("about",l)}">{t["aboutlink"]}{A}</a></div></div><div class="steps">{steps}</div></div></section>'

def home(l,t):
 c={
 "sq":{"title":["Ide të mëdha.","Zgjidhje reale."],"kicker":"NJË PERSPEKTIVË E RE PËR BIZNESIN TËND","intro":"Ndërtojmë faqe që bien në sy, sisteme që ta lehtësojnë punën dhe teknologji që të mban përpara.","cta":"Le ta ndërtojmë","scroll":"Shiko më poshtë","services":["Web & dizajn","Softuer & AI","IT & siguri"],"headline":"Çfarë vjen më pas?","lead":"Zgjidh atë që dëshiron të përmirësosh. Ne e kthejmë në një plan të qartë.","tabs":["Të dallohem.","Të punoj më mirë.","Të kem siguri."],"panel":["Një prezencë që nuk kalon pa u vënë re.","Më pak rrëmujë. Më shumë mundësi.","Teknologjia në duar të sigurta."],"names":["Websites.\nIdentitet.\nMarketing.","Softuer.\nAplikacione.\nAI.","Mbështetje.\nSiguri.\nMirëmbajtje."],"link":"Gjej zgjidhjen tënde","studio":"Dizajn + Teknologji","intro2":"Nga ideja e parë, te çdo ditë pune."},
 "en":{"title":["Big ideas.","Real solutions."],"kicker":"A FRESH PERSPECTIVE FOR YOUR BUSINESS","intro":"We build websites that get noticed, systems that make work easier and technology that keeps you moving.","cta":"Let’s build it","scroll":"Explore below","services":["Web & design","Software & AI","IT & security"],"headline":"What’s next?","lead":"Choose what you want to improve. We’ll turn it into a clear plan.","tabs":["Stand out.","Work better.","Stay protected."],"panel":["A presence that doesn’t go unnoticed.","Less friction. More possibilities.","Your technology in capable hands."],"names":["Websites.\nIdentity.\nMarketing.","Software.\nApplications.\nAI.","Support.\nSecurity.\nMaintenance."],"link":"Find your solution","studio":"Design + Technology","intro2":"From the first idea to the everyday."},
 "de":{"title":["Große Ideen.","Echte Lösungen."],"kicker":"EINE NEUE PERSPEKTIVE FÜR IHR UNTERNEHMEN","intro":"Wir entwickeln Websites, die auffallen, Systeme, die Arbeit erleichtern, und Technologie, die Sie weiterbringt.","cta":"Gemeinsam entwickeln","scroll":"Mehr entdecken","services":["Web & Design","Software & KI","IT & Sicherheit"],"headline":"Was kommt als Nächstes?","lead":"Wählen Sie, was Sie verbessern möchten. Wir machen daraus einen klaren Plan.","tabs":["Auffallen.","Besser arbeiten.","Sicher bleiben."],"panel":["Ein Auftritt, der in Erinnerung bleibt.","Weniger Reibung. Mehr Möglichkeiten.","Ihre Technologie in guten Händen."],"names":["Websites.\nIdentität.\nMarketing.","Software.\nAnwendungen.\nKI.","Support.\nSicherheit.\nWartung."],"link":"Die passende Lösung","studio":"Design + Technologie","intro2":"Von der ersten Idee bis zum Arbeitsalltag."}
 }[l]
 chips="".join(f'<a href="{route("services",l)}#{anchor}">{label}</a>' for label,anchor in zip(c["services"],["presence","operations","support"]))
 tabs="";panels=""
 for i,anchor in enumerate(["presence","operations","support"]):
  tabs+=f'<button class="need-tab" id="need-tab-{i}" role="tab" aria-controls="need-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}"><span class="need-tab-number">0{i+1}</span><span>{c["tabs"][i]}</span><span class="tab-arrow" aria-hidden="true">↗</span></button>'
  words="".join(f'<span>{esc(word)}</span>' for word in c["names"][i].split("\n"))
  panels+=f'<section class="need-panel panel-{i}" id="need-panel-{i}" role="tabpanel" aria-labelledby="need-tab-{i}" tabindex="0" {"" if i==0 else "hidden"}><div class="panel-poster" aria-hidden="true"><span class="poster-index">0{i+1} / IT DEPARTMENT</span><div>{words}</div><span class="poster-mark">↗</span></div><div class="need-panel-copy"><p class="eyebrow">{c["services"][i]}</p><h3>{c["panel"][i]}</h3><p>{t["groups"][i][1]}</p><a class="text-link" href="{route("services",l)}#{anchor}">{c["link"]}{A}</a></div></section>'
 hero=f'''<section class="studio-hero wrap"><div class="hero-topline"><p class="eyebrow"><span class="red-dot"></span>{c["kicker"]}</p><span>{t["location"]}</span></div><h1><span>{c["title"][0]}</span><span>{c["title"][1]}</span></h1><div class="hero-bottom"><div class="hero-services">{chips}</div><p>{c["intro"]}</p><a class="hero-cta" href="{route("contact",l)}"><span class="round-arrow" aria-hidden="true">↗</span><span>{c["cta"]}</span></a></div></section>'''
 return hero+work(l,t,True)+f'''<section class="needs-section wrap" id="solutions"><div class="section-heading"><div><p class="eyebrow">{t["services"]}</p><h2>{c["headline"]}</h2></div><p>{c["lead"]}</p></div><div class="needs-explorer"><div class="need-tabs" role="tablist" aria-label="{t["services"]}" aria-orientation="horizontal">{tabs}</div><div class="need-panels">{panels}</div></div></section>'''+process(l,t)+ending(l,t)

def cards(nodes,l,t):
 return '<div class="editorial-grid">'+''.join(f'<article><span class="step-number">{i+1:02d}</span><h3>{esc(cardtitle(n))}</h3>'+''.join(f'<p>{esc(p)}</p>' for p in paragraphs(n)[:1])+('<ul>'+''.join(f'<li>{esc(li.text())}</li>' for li in n.find("li"))+'</ul>' if n.find("li") else '')+'</article>' for i,n in enumerate(nodes))+'</div>'

